### ISSUE TITLE
Increase of withered plant return

### ISSUE THREAD

**Issue by chaosvolt** [DangerNoodle/mining-mod#11]
See PR idea Noct had here: https://github.com/CleverRaven/Cataclysm-DDA/pull/21853

Idea was basically that the whole "get withered plants for making stuff innawoods" feature is kinda badly-balanced. Problem is that bashing is kind of a dumb way to do it.

Unfortunately seems it was closed because all alternatives weren't easy to code. Hell, I wouldn't have much luck doing it either even if I was able to try.

Points raised in the PR discussion:
* Having to bash plants to get withered plants isn't ideal.
* Too many prompts to get those withered plants is bad.
* Being able to destroy underbrush accidentally is also bad. Smol problem here is this kiiinda conflicts with above point, due to a point I'll make below.

Now, some points I'll raise here:
* Underbrush kinda NEEDS to be a source of withered plants, as they're the primary source. Shrubs alone contribute about as much as randomly finding the bloody things in foraging.
* Any improvement over the status quo is a good one, and that goes double if the best solution isn't clear yet, or isn't likely to be implemented. An excellent example is the block thing that got you banned. I don't see anyone actually investing effort into fixing small shields the way Kevin wanted them.

Opening issue here because your mod's the one most-affected by this issue, and because nowhere else to open this. Also pinging @Coolthulhu for suggestions on what the sanest way to improve things would be, and to bounce ideas off them.

**Comment by Coolthulhu** [comment]
As I said in the PR discussion on CleverRaven: the bashing shrub thing is terrible not because bashing is inherently bad, but because it takes a ton of clicks.
An autobash or harvest action would solve it, but both of those require C++ (or lua). I don't see a good way to fix it with json alone, though a relatively low-C++ way would be to alter the trash drops from plants to happen 100% of the time, then make them not drop anything most of the time, but drop withered plants often when it actually drops things. Possibly making them drop bundles of withered plants rarely instead of single plants often.

**Comment by chaosvolt** [comment]
Hmm. Autobash does sound like the best option. Only problem is I dunno how to implement that, even if I was still a contributor. I know bashing corpses continues until completion, but that'd work on different mechanics, right? I don't know if that is in any way useful to the actual coding idea there.

Harvesting would be more complex as well, unsure how that would work code-wise.

That idea you just mentioned about foraging though, that sounds like it's got potential? What if obtaining withered plants was instead done via a third potential item returned, separate from the forage itemgroup and the trash itemgroup? Something like a fixed 0-3 (or whatever amount is sane).

If you additionally add an all-JSON way of harvesting from plain shrubs, then the "get withered plants from destroying underbrush" can either be left as-is (more as a consequence of permanently destroying a resource) or it can simply be removed.

I could look it up in the source and rather easily determine how to implement that, though rather obviously neither me nor the snek here can PR it.

**Comment by chaosvolt** [comment]
Also while I'm at it Coolthulhu, ever thought about including dangernoodle's blocking changes in the patch? From what I saw, you two seemed to be more or less on the same page right up until Kevin butted in, so it seems like you two had the right idea.

I mean it's not like any other way to make smol shields stop being dead weight is going to be added anytime soon. :V

**Comment by DangerNoodle** [comment]
I see. My apologies to @Coolthulhu for having implemented that idea in the first place. Never really was the ideal solution, but had been the best I could devise at the time.
