### ISSUE TITLE
Mineral veins generating less frequently than they should, espeically in zero-size cities

### ISSUE THREAD

**Issue by DangerNoodle** [DangerNoodle/mining-mod#12]
This came about after discussion over email with @chaosvolt, who has been playtesting this mod as of late, during my recent period of inactivity. Part of their current enabling as a collaborator for the time being.

Mineral veins have severe difficulty generating at present, despite all tested efforts to enable their generation. Generally a given overmap does not even contain the minimum demanded by the overmap specials. This problem is exacerbated when cities are set to 0, along with many vanilla areas that should be showing up but do not.

While their appearances are less limited when cities are enabled, it has been determined for the time being that overriding occurrences of existing specials, the method @pisskop discovered, is presently not worth the potential mod interactions and incompatibilities. As such Chaosvolt advocated their removal and a reduction in the minimums. As I have been rather busy with offline concerns as of late, I have enabled them as a collaborator, and will invite @BorkBorkGoesTheCode as well.

I do however request that major changes be made in the form of a pull request first rather than a direct commit, even if self-merged in my absence, for ease of tracking changes.

**Comment by BorkBorkGoesTheCode** [comment]
An unexpected bad crash during random character generation is preventing tests with 7081, but I could see what can be done with the older ones.

**Comment by chaosvolt** [comment]
Part of it's probably also https://github.com/CleverRaven/Cataclysm-DDA/issues/22827

**Comment by BorkBorkGoesTheCode** [comment]
A fix for overmap specials was merged recently. https://github.com/CleverRaven/Cataclysm-DDA/pull/24860

**Comment by chaosvolt** [comment]
Any tests so far with mining mod? Might give it a look if dangernoodle isn't on by tomorrow.

**Comment by chaosvolt** [comment]
![yeehaw](https://user-images.githubusercontent.com/11582235/44289434-d24e9100-a239-11e8-80f2-9c7b00b26b71.png)

Yep, this looks like a good improvement. Might be acceptable to close, I hope.

**Comment by DangerNoodle** [comment]
My apologies for having been absent for so long.

You are right, it does appear to be resolved. Thank you.
