### ISSUE TITLE
Anvil quality now exists, grip quality to possibly follow

### ISSUE THREAD

**Issue by smolbird** [DangerNoodle/mining-mod#13]
See pull request by @BorkBorkGoesTheCode: https://github.com/CleverRaven/Cataclysm-DDA/pull/23637

Notable is the change adding anvil quality to boulders. Up to you if mining to improve a boulder's utility as an anvil is worth keeping, but might warrant it being level 2 instead.

**Comment by DangerNoodle** [comment]
Thank you for that. As stone anvils retain utility in being able to drag them around, I retained the feature of being able to improve them with mining tools. Currently this also makes them anvil quality of 2 as well, but I would like to ask @BorkBorkGoesTheCode whether this is a good idea or not.

In addition I made copper picks require an anvil quality of 1, stone seems like it would be adequate for relatively malleable copper, in contrast to bronze. I do not yet know what their planned conventions are at present.

**Comment by BorkBorkGoesTheCode** [comment]
@DangerNoodle Spending time converting a rough boulder which represents every possible shape boulders have into a proper anvil with better stats is a good idea.

I'm going to split the ANVIL quality into anvil hardness, anvil refinement, and anvil versatility at a later date. The current anvil system is very gamey. I'm still learning about smithing, so all of this may change. I might add size.

**Comment by chaosvolt** [comment]
This seems to have gone nowhere, so it's probably safe to close by now?
