### ISSUE TITLE
A recent update broke your mod

### ISSUE THREAD

**Issue by ghost** [DangerNoodle/mining-mod#17]
@DangerNoodle starting a game with your mod now gives errors like this in 0.D-3181-g339945f:

![debug_message](https://user-images.githubusercontent.com/47664500/57989252-fcddac80-7a4c-11e9-87b4-dcf1da6aaecf.png)

@chaosvolt do you know if @DangerNoodle is still working on this mod?

**Comment by chaosvolt** [comment]
Ack. Sorry for having not responded, I've been busy too lately. Haven't heard from them in a while, seems to be why @BorkBorkGoesTheCode and I were left as maintainers? Working on a quickfix and had some ideas of my own that came from my experience with Dorf Life lately, might tackle that afterward if DN doesn't come back on to suggest anything.
