### ISSUE TITLE
Terrain descriptions are mandatory now

### ISSUE THREAD

**Issue by ghost** [DangerNoodle/mining-mod#19]
A bikeshedding PR made terrain descriptions mandatory.

**Comment by GitGodScrub** [comment]
I commited a fix, currently awaiting approval on the pull request.

**Comment by chaosvolt** [comment]
Will go ahead and merge it for DN then.

**Comment by chaosvolt** [comment]
Closed due to https://github.com/DangerNoodle/mining-mod/pull/20 :3
