### ISSUE TITLE
error on new game

### ISSUE THREAD

**Issue by ghostwalker788** [DangerNoodle/mining-mod#34]
DEBUG    : Error: data/mods//Mining_Mod/construction.json: line 3:12: unrecognized JSON object

[
  {
    "type":
           ^
            "construction_group",
    "id": "make_stone_anvil",
    "name": "Make Stone Anvil"

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

I'm just trying to load with a few mods spent two hours googling and found nothing helpful Idk how to fix it.

**Comment by chaosvolt** [comment]
You're using an old version of CDDA with the more up-to-date versions of Mining Mod. Never got the chance to set aside stable releases of this mod since I've been barely able to keep up with my own mods.
