### ISSUE TITLE
Empty bone pickaxe and auto mine terrain feature softlocks

### ISSUE THREAD

**Issue by brassmaster2357** [DangerNoodle/mining-mod#40]
### Problem
I was playing an innawoods playthrough in Cataclysm, using the Mining Mod among other things not relevant to this issue. I was using the "Auto mine terrain" feature to dig out a small room underground to stay cool/warm. However, when the bone pickaxe ran out of charges, I didn't know and tried to mine another chunk of terrain. The alert telling me I didn't have enough charges appeared every frame and I couldn't do anything, I assume because the game kept trying to mine the tile even though I couldn't.
### Suggestion
Maybe there's a way to tell the player they have no charges on their bone pickaxe? Perhaps there's also a way to break the pickaxe once it runs out of charges, since you can't recharge it?

**Comment by chaosvolt** [comment]
That's a C++ issue. First, automine should be acting sanely when it runs out of charges because jackhammers require charges too. Second, the code has no support for consumable tools except for active items that lack a revert entry.

**Comment by chaosvolt** [comment]
Looking into it, it's definitely an issue in DDA, in BN it seems to simply freeze instead of spam messages. I've tried a few different things to fix it, far as I can tell neither game seems to like having it call the pickaxe action from an item with charges. :/
