### ISSUE TITLE
Various field name errors (0.F-3)

### ISSUE THREAD

**Issue by Outcognito** [DangerNoodle/mining-mod#44]
![image](https://user-images.githubusercontent.com/31615562/167301572-26604e04-8af0-423e-ade8-2ff65b6ddc7a.png)
![image](https://user-images.githubusercontent.com/31615562/167301581-1c8f35ea-f364-413a-9b4f-0d93ad9eaee3.png)
![image](https://user-images.githubusercontent.com/31615562/167301587-09884e3d-e722-47da-8fa6-f970ee5c6405.png)
![image](https://user-images.githubusercontent.com/31615562/167301591-624357f9-689e-4785-a118-dcbbb4a150ef.png)
![image](https://user-images.githubusercontent.com/31615562/167301598-daa79bbe-3c3c-4419-9215-14ab097978ce.png)
![image](https://user-images.githubusercontent.com/31615562/167301609-40424c58-aec5-4c84-a442-d78ea03c63b9.png)
[debug.log](https://github.com/DangerNoodle/mining-mod/files/8647167/debug.log)

**Comment by chaosvolt** [comment]
Ah crap, issue is basically the master version of this mod is for recent builds, and there isn't a 0.F stable version set aside.

**Comment by chaosvolt** [comment]
And implemented: https://github.com/DangerNoodle/mining-mod/releases/tag/0.F-3
