### ISSUE TITLE
CDDA Experimental Mining mod incompability

### ISSUE THREAD

**Issue by Pavelgon4ik** [DangerNoodle/mining-mod#55]
![image](https://github.com/user-attachments/assets/447fbc19-6c5e-4a1e-b24c-9ba900fa221e)

Starting with a certain version of experimental cataclysm (sometime this month), the mod stops working, but is fixed with a simple crutch by replacing the line in modinfo.json inside mining mod in cdda mod folder from ident to id, and the mod is compatible again.

![image](https://github.com/user-attachments/assets/d33fb5ab-f9bd-40f3-aca8-d26cea45595b)
![image](https://github.com/user-attachments/assets/cc8e9a2c-5e00-4ef5-9435-0ba55b30307a)

**Comment by Pavelgon4ik** [comment]
@DangerNoodle Since I can't add this fix on this repository, I kindly ask you to update repository with this new fix

**Comment by chaosvolt** [comment]
They haven't been active in a fair while but I've been maintaining it, so will fix in a sec.

**Comment by chaosvolt** [comment]
That reminds me I should check all of my mods for that, I think I fixed up Arcana as well as updating Cata++ for Noct but might've forgotten a few other mods.

**Comment by Pavelgon4ik** [comment]
Thanks man. Good luck with your mods
